name: "Conventional Commit"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  id-token: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          requireScope: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
